package com.mycompany.astroweather.util

object WeatherConstants {
    val weather = mapOf(
        0 to "tornado",
        1 to "tropical storm",
        2 to "hurricane",
        3 to "severe thunderstorms",
        4 to "thunderstorms",
        5 to "mixed rain and snow",
        6 to "mixed rain and sleet",
        7 to "mixed snow and sleet",
        8 to "freezing drizzle",
        9 to "drizzle",
        10 to "freezing rain",
        11 to "showers",
        12 to "rain",
        13 to "snow flurries",
        14 to "light snow showers",
        15 to "blowing snow",
        16 to "snow",
        17 to "hail",
        18 to "sleet",
        19 to "dust",
        20 to "foggy",
        21 to "haze",
        22 to "smoky",
        23 to "blustery",
        24 to "windy",
        25 to "cold",
        26 to "cloudy",
        27 to "mostly cloudy (night)",
        28 to "mostly cloudy (day)",
        29 to "partly cloudy (night)",
        30 to "partly cloudy (day)",
        31 to "clear (night)",
        32 to "sunny",
        33 to "fair (night)",
        34 to "fair (day)",
        35 to "mixed rain and hail",
        36 to "hot",
        37 to "isolated thunderstorms",
        38 to "scattered thunderstorms",
        39 to "scattered showers (day)",
        40 to "heavy rain",
        41 to "scattered snow showers (day)",
        42 to "heavy snow",
        43 to "blizzard",
        44 to "not available",
        45 to "scattered showers (night)",
        46 to "scattered snow showers (night)",
        47 to "scattered thundershowers"
    )
}